/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations, SpotLight } from "@react-three/drei";
import { useThree } from "@react-three/fiber";
import { LayerMaterial, Depth, Color, Fresnel } from "lamina";
import { Object3D } from "three";
import * as THREE from "three";
type Props = {
  position: Array<number>;
};

export default function EmptyCup({ position }: Props) {
  const group = useRef<Object3D<Event> | undefined>(undefined);
  const { nodes, materials, animations } = useGLTF("/models/cup.glb");

  return (
    <group
      position={new THREE.Vector3(position[0], position[1], position[2])}
      dispose={null}
    >
      <group name="Scene" scale={0.4} rotation={[0.6, Math.PI, -0.3]}>
        <group ref={group} name="Cup">
          <mesh
            name="Circle007"
            castShadow
            receiveShadow
            geometry={(nodes.Circle007 as THREE.Mesh).geometry}
          >
            <LayerMaterial color="#271692">
              <Color color={"#271692"} />
              <Depth
                far={3}
                origin={[1, 1, 1]}
                colorA="#ffffff"
                colorB="#271692"
                alpha={0.03}
                mode={"lighten"}
                mapping="camera"
              />
              <Depth
                near={0.25}
                far={2}
                colorA={"#271692"}
                alpha={0.5}
                mode={"lighten"}
                mapping={"vector"}
              />
              <Fresnel mode={"softlight"} />
            </LayerMaterial>
          </mesh>
          <mesh
            name="Circle007_1"
            castShadow
            receiveShadow
            geometry={(nodes.Circle007_1 as THREE.Mesh).geometry}
          >
            <LayerMaterial color="#271692">
              <Color color={"#271692"} />
              <Depth
                far={3}
                origin={[1, 1, 1]}
                colorA="#ffffff"
                colorB="#271692"
                alpha={0.03}
                mode={"lighten"}
                mapping="camera"
              />
              <Depth
                near={0.25}
                far={2}
                colorA={"#271692"}
                alpha={0.5}
                mode={"lighten"}
                mapping={"vector"}
              />
              <Fresnel mode={"softlight"} />
            </LayerMaterial>
          </mesh>
          <mesh
            name="Circle007_2"
            castShadow
            receiveShadow
            geometry={(nodes.Circle007_2 as THREE.Mesh).geometry}
          >
            <meshStandardMaterial
              metalness={1.0}
              roughness={0.1}
              color={"white"}
            />
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/cup.glb");
