/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, Ref } from "react";
import { GroupProps } from "@react-three/fiber";
import { useGLTF, MeshWobbleMaterial } from "@react-three/drei";
import { motion as motion3d } from "framer-motion-3d";
import * as THREE from "three";

import { LayerMaterial, Depth, Color, Fresnel } from "lamina";

type Props = {
  position: Array<number>;
};
export default function Cup({ position = [0, 0, 0] }: Props) {
  const group = useRef<GroupProps>();
  const cup = useRef(null);
  const { nodes } = useGLTF("/models/tea-cup.gltf");

  return (
    <motion3d.group
      ref={group as Ref<GroupProps>}
      position={new THREE.Vector3(position[0], position[1], position[2])}
      dispose={null}
    >
      <group
        scale={0.5}
        name="Tea"
        ref={cup}
        rotation={[0, -1.0, -0.66]}
        position={[0, 0, 0]}
      >
        <mesh
          name="Sphere002"
          castShadow
          receiveShadow
          geometry={(nodes.Sphere002 as THREE.Mesh).geometry}
        >
          <LayerMaterial color="#271692">
            <Color color={"#271692"} />
            <Depth
              far={3}
              origin={[1, 1, 1]}
              colorA="#ffffff"
              colorB="#271692"
              alpha={0.03}
              mode={"lighten"}
              mapping="camera"
            />
            <Depth
              near={0.25}
              far={2}
              colorA={"#271692"}
              alpha={0.5}
              mode={"lighten"}
              mapping={"vector"}
            />
            <Fresnel mode={"softlight"} />
          </LayerMaterial>
        </mesh>
        <mesh
          name="Sphere002_1"
          castShadow
          receiveShadow
          geometry={(nodes.Sphere002_1 as THREE.Mesh).geometry}
        >
          <LayerMaterial color="#271692">
            <Color color={"#271692"} />
            <Depth
              far={3}
              origin={[1, 1, 1]}
              colorA="#ffffff"
              colorB="#271692"
              alpha={0.03}
              mode={"lighten"}
              mapping="camera"
            />
            <Depth
              near={0.25}
              far={2}
              colorA={"#271692"}
              alpha={0.5}
              mode={"lighten"}
              mapping={"vector"}
            />
            <Fresnel mode={"softlight"} />
          </LayerMaterial>{" "}
        </mesh>

        <mesh
          name="Sphere002_2"
          castShadow
          receiveShadow
          geometry={(nodes.Sphere002_2 as THREE.Mesh).geometry}
        >
          <MeshWobbleMaterial
            blending={THREE.AdditiveBlending}
            color={"#ffffff"}
            opacity={0.3}
            factor={3}
            speed={0.5}
          />
        </mesh>
      </group>
    </motion3d.group>
  );
}

useGLTF.preload("/models/tea-cup.gltf");
