import * as THREE from "three";
import React, { Suspense, useRef } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import { useGLTF, Html } from "@react-three/drei";

import Hero from "./Hero";
type Props = {
  props?: Object;
  position: Array<number>;
};

export default function Laptop({ props, position }: Props) {
  const group = useRef(null);
  // Load model
  const { nodes, materials } = useGLTF("/models/mac-draco.glb");

  // The jsx graph was auto-generated by: https://github.com/pmndrs/gltfjsx
  return (
    <group
      ref={group}
      {...props}
      position={new THREE.Vector3(position[0], position[1], position[2])}
      dispose={null}
    >
      <group rotation-x={-0.425}>
        <group position={[0, 2.96, -0.13]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            material={materials.aluminium}
            geometry={nodes["Cube008"].geometry}
          />
          <mesh
            material={materials["matte.001"]}
            geometry={nodes["Cube008_1"].geometry}
          />
          <mesh geometry={nodes["Cube008_2"].geometry}>
            <meshStandardMaterial
              color={"#1d1d1d"}
              emissive={"#220033"}
              emissiveIntensity={3}
            />
          </mesh>
        </group>
      </group>
      <mesh
        material={materials.keys}
        geometry={(nodes.keyboard as THREE.Mesh).geometry}
        position={[1.79, 0, 3.45]}
      />
      <group position={[0, -0.1, 3.39]}>
        <mesh
          material={materials.aluminium}
          geometry={(nodes["Cube002"] as THREE.Mesh).geometry}
        />
        <mesh
          material={materials.trackpad}
          geometry={(nodes["Cube002_1"] as THREE.Mesh).geometry}
        />
      </group>
      <mesh
        material={materials.touchbar}
        geometry={(nodes.touchbar as THREE.Mesh).geometry}
        position={[0, -0.03, 1.2]}
      />
    </group>
  );
}
