/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations, Html } from "@react-three/drei";
import Contact from "./Contact";

type Props = {
  props?: any;
};
export default function Mail({ props }: Props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/message.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          position={[0, -2, -2]}
          name="Mail"
          castShadow
          receiveShadow
          //@ts-ignore
          geometry={nodes.Mail?.geometry}
        />
        <meshNormalMaterial />
      </group>
      <Html position={[0, 0, 0]} fullscreen>
        <Contact />
      </Html>
    </group>
  );
}

useGLTF.preload("/models/message.glb");
